name: My Workflow

on:
  workflow_dispatch:

jobs:
  
  
  
  job1:
   
     uses: ./.github/workflows/Precoditions.yml
  
  
        
  job2:
    
   runs-on: ubuntu-latest
   needs: job1
   steps:
       - uses: actions/checkout@v3
       - run: npm ci
       - run: npm run build --if-present
       - name: Run test
         run: npm run qaWolf




  job3:
        needs: job2
        if: always()
        uses: ./.github/workflows/Postconditions.yml
